alias bashrc="vim ~/.bashrc"
alias aliases="vim ~/.bash_aliases"
alias c="clear"
alias get2work="cd ~/Documents/Code/Flashservice && rvm gemset use flash"
alias koans="cd ~/Documents/Code/Koans && rake"
